//
//  ChartsTableViewControllerInteractor.swift
//  Prueba Upax
//
//  Created Ivan Soriano on 31/05/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChartsTableViewControllerInteractor: ChartsTableViewControllerInteractorProtocol {

    weak var presenter: ChartsTableViewControllerPresenterProtocol?
    
    func callService(_ callback: @escaping (ResponseData) -> Void) {
        guard let url = URL(string: "https://s3.amazonaws.com/dev.drive/test.json") else {
            debugLog("Invalid link", in: .networking)
            return
        }
        let request = URLRequest(url: url)
        
        let task = URLSession.shared.dataTask(with: request) { data, response, error in
            guard error == nil else {
                debugLog("Error in Network Request", in: .networking, with: error)
                return
            }
            
            guard let response = response as? HTTPURLResponse, response.statusCode == 200 else {
                debugLog("Non-200 Response Status Code", in: .networking)
                return
            }
            
            guard let data = data else {
                debugLog("There's no Data in the Response", in: .networking)
                return
            }
            
            do {
                let response = try JSONDecoder().decode(ResponseData.self, from: data)
                callback(response)
            } catch {
                print(String(describing: error))
                debugLog("Unable to parse data", in: .networking, with: error)
            }
        }
        
        task.resume()
    }
}
