//
//  ChartsTableViewControllerPresenter.swift
//  Prueba Upax
//
//  Created Ivan Soriano on 31/05/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChartsTableViewControllerPresenter: ChartsTableViewControllerPresenterProtocol {
    
    weak private var view: ChartsTableViewControllerViewProtocol?
    var interactor: ChartsTableViewControllerInteractorProtocol?
    private let router: ChartsTableViewControllerWireframeProtocol
    
    init(interface: ChartsTableViewControllerViewProtocol, interactor: ChartsTableViewControllerInteractorProtocol?, router: ChartsTableViewControllerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func callService(){
        guard let interactor = interactor else { return }
        interactor.callService { [weak self] response in
            self?.view?.set(data: response)
        }
    }
}
