//
//  MainTableInteractor.swift
//  Prueba Upax
//
//  Created Ivan Soriano on 31/05/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainTableInteractor: MainTableInteractorProtocol {

    weak var presenter: MainTablePresenterProtocol?
}
