//
//  MainTablePresenter.swift
//  Prueba Upax
//
//  Created Ivan Soriano on 31/05/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainTablePresenter: MainTablePresenterProtocol {

    weak private var view: MainTableViewProtocol?
    var interactor: MainTableInteractorProtocol?
    private let router: MainTableWireframeProtocol

    init(interface: MainTableViewProtocol, interactor: MainTableInteractorProtocol?, router: MainTableWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
