//
//  MainTableProtocols.swift
//  Prueba Upax
//
//  Created Ivan Soriano on 31/05/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MainTableWireframeProtocol: class {

}
//MARK: Presenter -
protocol MainTablePresenterProtocol: class {

}

//MARK: Interactor -
protocol MainTableInteractorProtocol: class {

  var presenter: MainTablePresenterProtocol?  { get set }
}

//MARK: View -
protocol MainTableViewProtocol: class {

  var presenter: MainTablePresenterProtocol?  { get set }
}
